### ISSUE TITLE
What Model did you use?

### ISSUE THREAD

**Issue by Deorbiting** [dheerajnbhat/Brain-Tumor-Detection#1]
Just wondering what model you used and the source of the model

Thanks

**Comment by ashuvssut** [comment]
Hi @Deorbiting, did you find the source of the model that @dheerajnbhat used?
[brain_tumor_detector.h5](https://github.com/dheerajnbhat/Brain-Tumor-Detection/blob/master/brain_tumor_detector.h5)

**Comment by dheerajnbhat** [comment]
Hi,

I have custom trained the model using tensorflow framework. If you need to
use a different model, you can replace the model file.

Regards,
Dheeraj
